# Generated by Django 4.1.5 on 2024-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='default_image.png', upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
