# Generated by Django 4.1.5 on 2024-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_activity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.TextField(default='123'),
        ),
    ]
